### ISSUE TITLE
启用每日委托时报错

### ISSUE THREAD

**Issue by zzzqh** [infstellar/python-git-program-launcher#10]
2023-07-17 15:16:07.838 | INFO     | source.webio.webio:main:48 - webio启动完成
2023-07-17 15:16:41.286 | INFO     | source.api.pdocr_api:<module>:4 - 正在创建OCR对象
2023-07-17 15:16:41.717 | CRITICAL | source.api.pdocr_api:<module>:14 - 导入paddleocr时错误; err code: 001
2023-07-17 15:16:41.727 | ERROR    | source.api.pdocr_api:<module>:15 - FastDeploy initalized failed! Error: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):

  File "G:\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\lib\site-packages\fastdeploy\c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *

ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 890, in _bootstrap

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 926, in _bootstrap_inner

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\common\base_threading.py", line 170, in run
    self.loop()
    │    └ <function TaskManager.loop at 0x0000000003E6F798>
    └ <TaskManager(TaskManager, started daemon 6372)>

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\task\task_manager.py", line 130, in loop
    self.start_stop_task(i)
    │    │               └ 'CommissionTask'
    │    └ <function TaskManager.start_stop_task at 0x0000000003E6F4C8>
    └ <TaskManager(TaskManager, started daemon 6372)>

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\task\task_manager.py", line 91, in start_stop_task
    from source.commission.commission_executor import CommissionExecutor

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\commission\commission_executor.py", line 1, in <module>
    from source.commission.util import *

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\commission\util.py", line 3, in <module>
    from source.mission.mission_template import ERR_FAIL

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\mission\mission_template.py", line 1, in <module>
    from source.teyvat_move import teyvat_move_flow_upgrade

  File "<frozen importlib._bootstrap>", line 1035, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\teyvat_move\teyvat_move_flow_upgrade.py", line 5, in <module>
    from source.pickup.pickup_operator import PickupOperator

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\pickup\pickup_operator.py", line 4, in <module>
    from source.api.pdocr_complete import ocr

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\api\pdocr_complete.py", line 1, in <module>
    from source.api.pdocr_api import PaddleOcrFastDeploy

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

> File "G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\api\pdocr_api.py", line 12, in <module>
    import fastdeploy

  File "G:\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\lib\site-packages\fastdeploy\__init__.py", line 122, in <module>
    from .c_lib_wrap import (

  File "G:\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\lib\site-packages\fastdeploy\c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")

RuntimeError: FastDeploy initalized failed! Error: DLL load failed: 找不到指定的模块。
2023-07-17 15:16:41.942 | INFO     | source.api.pdocr_api:<module>:16 - import pdocr time: 0.65
2023-07-17 15:16:42.037 | INFO     | source.api.pdocr_api:__init__:50 - Creating PaddleOCRFastDeploy object: G:\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\assets\PPOCRModels\zh_CN

**Comment by infstellar** [comment]
CPU是否支持AVX指令集

**Comment by zzzqh** [comment]
支持，I7 4710 MQ

**Comment by infstellar** [comment]
不清楚，可能是C++依赖没有装全？安装C++Runtime或者用Visual Studio安装C++全家桶试试
或者在网上搜索怎么解决
```
from .libs.fastdeploy_main import *
ImportError: DLL load failed: 找不到指定的模块。
```
