### ISSUE TITLE
关闭了所有加速器，但是还这样报错？

### ISSUE THREAD

**Issue by linkkkkg** [infstellar/python-git-program-launcher#12]
"E:\PGPL-2.0\PGPL-2.0.0"
zh_CN
python "E:\PGPL-2.0\PGPL-2.0.0/translation/msgfmt.py" -o "E:\PGPL-2.0\PGPL-2.0.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "E:\PGPL-2.0\PGPL-2.0.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
zh_CN
Running on all addresses.
Use http://192.168.10.3:22269/ to access the application
2023-07-17 22:30:42.612 | INFO     | webio:main:35 - webio started
js: Error(%s) in dispatch command: %s TypeError: Cannot read property 'update_input' of undefined pin_update
2023-07-17 22:30:43.532 | INFO     | logger:hr:73 - +------------------------------------------------------------------------------+
2023-07-17 22:30:43.533 | INFO     | logger:hr:74 - |                    WELCOME TO PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-07-17 22:30:43.534 | INFO     | logger:hr:75 - +------------------------------------------------------------------------------+
2023-07-17 22:30:43.534 | INFO     | logger:hr:69 - <<< 该程序在GITHUB免费开源 >>>
2023-07-17 22:30:43.535 | INFO     | logger:hr:69 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查 看使用说明 >>>
2023-07-17 22:30:43.544 | INFO     | utils:execute:197 - "E:/PGPL-2.0/PGPL-2.0.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r E:/PGPL-2.0/PGPL-2.0.0/toolkit/basic_requirements.txt
Requirement already satisfied: lxml in e:\pgpl-2.0\pgpl-2.0.0\toolkit\python\3.7.6_gia_launcher_download_lib\lib\site-packages (from -r E:/PGPL-2.0/PGPL-2.0.0/toolkit/basic_requirements.txt (line 1)) (4.9.3)
Requirement already satisfied: future in e:\pgpl-2.0\pgpl-2.0.0\toolkit\python\3.7.6_gia_launcher_download_lib\lib\site-packages (from -r E:/PGPL-2.0/PGPL-2.0.0/toolkit/basic_requirements.txt (line 2)) (0.18.3)
Requirement already satisfied: urllib3 in e:\pgpl-2.0\pgpl-2.0.0\toolkit\python\3.7.6_gia_launcher_download_lib\lib\site-packages (from -r E:/PGPL-2.0/PGPL-2.0.0/toolkit/basic_requirements.txt (line 3)) (2.0.3)
2023-07-17 22:30:44.023 | INFO     | utils:execute:209 - [ success ]
2023-07-17 22:30:44.024 | INFO     | logger:hr:73 - +-------------------------------------------------+
2023-07-17 22:30:44.025 | INFO     | logger:hr:74 - |                    PYTHON已安装                    |
2023-07-17 22:30:44.025 | INFO     | logger:hr:75 - +-------------------------------------------------+
2023-07-17 22:30:44.026 | INFO     | pages:_start:113 - {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'genshin_assistant.py', 'PypiMirror': 'AUTO', 'PythonMirror': 'AUTO', 'PythonVersion': '3.7.6', 'Repository': 'https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib', 'RequirementsFile': 'requirements.txt', 'Tag': ''}
2023-07-17 22:30:44.027 | INFO     | logger:hr:69 - <<< 启动中... >>>
2023-07-17 22:30:44.028 | INFO     | logger:hr:73 - +--------------------------------------------------------------------------+
2023-07-17 22:30:44.028 | INFO     | logger:hr:74 - |                    UPDATE PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-07-17 22:30:44.029 | INFO     | logger:hr:75 - +--------------------------------------------------------------------------+
2023-07-17 22:30:44.030 | INFO     | logger:hr:73 - +----------------------------------------------+
2023-07-17 22:30:44.030 | INFO     | logger:hr:74 - |                    GIT初始化                    |
2023-07-17 22:30:44.031 | INFO     | logger:hr:75 - +----------------------------------------------+
2023-07-17 22:30:44.032 | INFO     | utils:execute:197 - "E:/PGPL-2.0/PGPL-2.0.0/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in E:/PGPL-2.0/PGPL-2.0.0/repositories/GIA_Launcher_Download_Lib/.git/
2023-07-17 22:30:44.091 | INFO     | utils:execute:209 - [ success ]
2023-07-17 22:30:44.093 | INFO     | logger:hr:65 - ==================== 设置GIT验证 ====================
2023-07-17 22:30:44.093 | INFO     | utils:execute:197 - "E:/PGPL-2.0/PGPL-2.0.0/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
2023-07-17 22:30:44.146 | INFO     | utils:execute:201 - [ allowed failure ], error_code: 5
2023-07-17 22:30:44.147 | INFO     | utils:execute:197 - "E:/PGPL-2.0/PGPL-2.0.0/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
2023-07-17 22:30:44.187 | INFO     | utils:execute:201 - [ allowed failure ], error_code: 5
2023-07-17 22:30:44.188 | INFO     | logger:hr:65 - ==================== 设置GIT仓库 ====================
2023-07-17 22:30:44.189 | INFO     | utils:execute:197 - "E:/PGPL-2.0/PGPL-2.0.0/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib
2023-07-17 22:30:44.231 | INFO     | utils:execute:209 - [ success ]
2023-07-17 22:30:44.231 | INFO     | logger:hr:65 - ==================== 获取仓库分支 ====================
2023-07-17 22:30:44.232 | INFO     | utils:execute:197 - "E:/PGPL-2.0/PGPL-2.0.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
error: cannot spawn sh: No such file or directory
fatal: could not read Username for 'https://gitee.com': No such file or directory
2023-07-17 22:30:44.595 | INFO     | utils:execute:204 - [ failure ], error_code: 128
2023-07-17 22:30:44.596 | INFO     | utils:show_error:164 - Update failed
2023-07-17 22:30:44.596 | INFO     | utils:show_error:166 -
2023-07-17 22:30:44.597 | INFO     | utils:show_error:167 - Last command: "E:/PGPL-2.0/PGPL-2.0.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
error_code: 128
2023-07-17 22:30:44.598 | WARNING  | utils:show_error:168 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-17 22:30:44.599 | WARNING  | utils:show_error:169 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-17 22:30:44.600 | WARNING  | utils:show_error:170 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-17 22:30:44.601 | ERROR    | main:git_repository_init:87 - An error has been caught in function 'git_repository_init', process 'MainProcess' (9548), thread 'Thread-4' (11560):
Traceback (most recent call last):

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001F54FB12678>
    └ <Thread(Thread-4, started daemon 11560)>

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001F54FB12438>
    └ <Thread(Thread-4, started daemon 11560)>

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x000001F55231FB88>}
    │    │        │    │        └ <Thread(Thread-4, started daemon 11560)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 11560)>
    │    └ <function put_buttons.<locals>.click_callback at 0x000001F55231F9D8>
    └ <Thread(Thread-4, started daemon 11560)>

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-SuO9W7Ek2b', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x000001F55231FB88>

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pages.MainPage object at 0x000001F55BB8CC88>>]

  File "E:\PGPL-2.0\PGPL-2.0.0\pages.py", line 119, in _start
    GitManager(launching_config, pt).git_install()
    │          │                 └ <main.ProgressTracker object at 0x000001F55BBA2D48>
    │          └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class 'main.GitManager'>

  File "E:\PGPL-2.0\PGPL-2.0.0\main.py", line 131, in git_install
    keep_changes=self.KeepLocalChanges,
                 │    └ False
                 └ <main.GitManager object at 0x000001F55F9038C8>

> File "E:\PGPL-2.0\PGPL-2.0.0\main.py", line 87, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
    │    └ <function Command.execute at 0x000001F55222BB88>
    └ <main.GitManager object at 0x000001F55F9038C8>

  File "E:\PGPL-2.0\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError
2023-07-17 22:30:44.719 | ERROR    | pages:_start:145 -
Traceback (most recent call last):

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001F54FB12678>
    └ <Thread(Thread-4, started daemon 11560)>

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001F54FB12438>
    └ <Thread(Thread-4, started daemon 11560)>

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x000001F55231FB88>}
    │    │        │    │        └ <Thread(Thread-4, started daemon 11560)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 11560)>
    │    └ <function put_buttons.<locals>.click_callback at 0x000001F55231F9D8>
    └ <Thread(Thread-4, started daemon 11560)>

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-SuO9W7Ek2b', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x000001F55231FB88>

  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pages.MainPage object at 0x000001F55BB8CC88>>]

> File "E:\PGPL-2.0\PGPL-2.0.0\pages.py", line 119, in _start
    GitManager(launching_config, pt).git_install()
    │          │                 └ <main.ProgressTracker object at 0x000001F55BBA2D48>
    │          └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class 'main.GitManager'>

  File "E:\PGPL-2.0\PGPL-2.0.0\main.py", line 131, in git_install
    keep_changes=self.KeepLocalChanges,
                 │    └ False
                 └ <main.GitManager object at 0x000001F55F9038C8>

  File "E:\PGPL-2.0\PGPL-2.0.0\main.py", line 87, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
    │    └ <function Command.execute at 0x000001F55222BB88>
    └ <main.GitManager object at 0x000001F55F9038C8>

  File "E:\PGPL-2.0\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError
Unhandled error in pywebio app
Traceback (most recent call last):
  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
  File "E:\PGPL-2.0\PGPL-2.0.0\pages.py", line 146, in _start
    raise e
  File "E:\PGPL-2.0\PGPL-2.0.0\pages.py", line 119, in _start
    GitManager(launching_config, pt).git_install()
  File "E:\PGPL-2.0\PGPL-2.0.0\main.py", line 131, in git_install
    keep_changes=self.KeepLocalChanges,
  File "E:\PGPL-2.0\PGPL-2.0.0\main.py", line 87, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
  File "E:\PGPL-2.0\PGPL-2.0.0\toolkit\lib\site-packages\loguru\_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "E:\PGPL-2.0\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
utils.ExecutionError

**Comment by infstellar** [comment]
尝试重启后重试

**Comment by linkkkkg** [comment]
那天怎么也不行，今天突然好了
