### ISSUE TITLE
启动程序时下载报错

### ISSUE THREAD

**Issue by Na-coco** [infstellar/python-git-program-launcher#19]
2023-07-29 10:42:40.131 | INFO     | logger:hr:69 - <<< 该程序在GITHUB免费开源 >>>
2023-07-29 10:42:40.132 | INFO     | logger:hr:69 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查 看使用说明 >>>
2023-07-29 10:42:40.140 | INFO     | utils:execute:197 - "F:/Genshin AI/PGPL-2.0.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r F:/Genshin AI/PGPL-2.0.0/toolkit/basic_requirements.txt
F:\Genshin AI\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe: No module named pip
2023-07-29 10:42:40.198 | INFO     | utils:execute:204 - [ failure ], error_code: 1
2023-07-29 10:42:40.199 | INFO     | utils:show_error:164 - Update failed
2023-07-29 10:42:40.199 | INFO     | utils:show_error:166 -
2023-07-29 10:42:40.200 | INFO     | utils:show_error:167 - Last command: "F:/Genshin AI/PGPL-2.0.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r F:/Genshin AI/PGPL-2.0.0/toolkit/basic_requirements.txt
error_code: 1
2023-07-29 10:42:40.201 | WARNING  | utils:show_error:168 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-29 10:42:40.202 | WARNING  | utils:show_error:169 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-29 10:42:40.204 | WARNING  | utils:show_error:170 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-29 10:42:40.205 | ERROR    | main:run:343 - An error has been caught in function 'run', process 'MainProcess' (1604), thread 'Thread-9' (5836):
Traceback (most recent call last):

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000214458039D8>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000021445803798>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x0000021448037558>}
    │    │        │    │        └ <Thread(Thread-9, started daemon 5836)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-9, started daemon 5836)>
    │    └ <function put_buttons.<locals>.click_callback at 0x00000214480375E8>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-Xqkg5Xz562', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x0000021448037558>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pages.MainPage object at 0x0000021450A9CD08>>]

  File "F:\Genshin AI\PGPL-2.0.0\pages.py", line 111, in _start
    PROGRAM_PYTHON_PATH = PythonManager(launching_config, pt).run()
                          │             │                 └ <main.ProgressTracker object at 0x0000021454585F08>
                          │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': True, 'Main': 'gen...
                          └ <class 'main.PythonManager'>

> File "F:\Genshin AI\PGPL-2.0.0\main.py", line 343, in run
    self.execute(f'"{self.python_path}" -m pip install -r {os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}')
    │    └ <function Command.execute at 0x0000021447F50438>
    └ <main.PythonManager object at 0x0000021454586088>

  File "F:\Genshin AI\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError
2023-07-29 10:42:40.247 | WARNING  | main:run:345 - pip失败，重装python
2023-07-29 10:42:40.256 | INFO     | utils:verify_path:111 - dir F:\Genshin AI\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib has been created
2023-07-29 10:42:40.259 | INFO     | main:download_python_zip:253 - url: https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip
2023-07-29 10:42:40.330 | INFO     | utils:download_url:65 - 下载url:https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip -> F:\Genshin AI\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip
F:\Genshin AI\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 0.00B [00:00, ?B/s]F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\urllib3\connectionpool.py:1102: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.huaweicloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  InsecureRequestWarning,
F:\Genshin AI\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 7.50MB [00:00, 13.8MB/s]
2023-07-29 10:42:40.878 | INFO     | logger:hr:73 - +--------------------------------------------------------+
2023-07-29 10:42:40.879 | INFO     | logger:hr:74 - |                    下载PYTHON成功，解压压缩包                    |
2023-07-29 10:42:40.880 | INFO     | logger:hr:75 - +--------------------------------------------------------+
2023-07-29 10:42:40.986 | INFO     | logger:hr:73 - +------------------------------------------------------+
2023-07-29 10:42:40.988 | INFO     | logger:hr:74 - |                    INSTALLING PIP                    |
2023-07-29 10:42:40.989 | INFO     | logger:hr:75 - +------------------------------------------------------+
2023-07-29 10:42:40.990 | INFO     | utils:execute:197 - "F:/Genshin AI/PGPL-2.0.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" F:/Genshin AI/PGPL-2.0.0/toolkit/get-pip.py --no-setuptools --no-wheel
F:/Genshin AI/PGPL-2.0.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe: can't open file 'F:/Genshin': [Errno 2] No such file or directory
2023-07-29 10:42:41.032 | INFO     | utils:execute:204 - [ failure ], error_code: 2
2023-07-29 10:42:41.033 | INFO     | utils:show_error:164 - Update failed
2023-07-29 10:42:41.034 | INFO     | utils:show_error:166 -
2023-07-29 10:42:41.035 | INFO     | utils:show_error:167 - Last command: "F:/Genshin AI/PGPL-2.0.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" F:/Genshin AI/PGPL-2.0.0/toolkit/get-pip.py --no-setuptools --no-wheel
error_code: 2
2023-07-29 10:42:41.037 | WARNING  | utils:show_error:168 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-29 10:42:41.038 | WARNING  | utils:show_error:169 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-29 10:42:41.040 | WARNING  | utils:show_error:170 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-29 10:42:41.041 | ERROR    | main:download_python_zip:263 - An error has been caught in function 'download_python_zip', process 'MainProcess' (1604), thread 'Thread-9' (5836):
Traceback (most recent call last):

  File "F:\Genshin AI\PGPL-2.0.0\main.py", line 343, in run
    self.execute(f'"{self.python_path}" -m pip install -r {os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}')
    │    └ <function Command.execute at 0x0000021447F50438>
    └ <main.PythonManager object at 0x0000021454586088>

  File "F:\Genshin AI\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000214458039D8>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000021445803798>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x0000021448037558>}
    │    │        │    │        └ <Thread(Thread-9, started daemon 5836)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-9, started daemon 5836)>
    │    └ <function put_buttons.<locals>.click_callback at 0x00000214480375E8>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-Xqkg5Xz562', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x0000021448037558>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pages.MainPage object at 0x0000021450A9CD08>>]

  File "F:\Genshin AI\PGPL-2.0.0\pages.py", line 111, in _start
    PROGRAM_PYTHON_PATH = PythonManager(launching_config, pt).run()
                          │             │                 └ <main.ProgressTracker object at 0x0000021454585F08>
                          │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': True, 'Main': 'gen...
                          └ <class 'main.PythonManager'>

  File "F:\Genshin AI\PGPL-2.0.0\main.py", line 348, in run
    self.download_python_zip()
    │    └ <function PythonManager.download_python_zip at 0x000002144802F678>
    └ <main.PythonManager object at 0x0000021454586088>

> File "F:\Genshin AI\PGPL-2.0.0\main.py", line 263, in download_python_zip
    self.execute(f'"{self.python_path}" {os.path.join(ROOT_PATH, "toolkit", "get-pip.py")} --no-setuptools --no-wheel')
    │    └ <function Command.execute at 0x0000021447F50438>
    └ <main.PythonManager object at 0x0000021454586088>

  File "F:\Genshin AI\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError
2023-07-29 10:42:41.091 | ERROR    | pages:_start:145 -
Traceback (most recent call last):

  File "F:\Genshin AI\PGPL-2.0.0\main.py", line 343, in run
    self.execute(f'"{self.python_path}" -m pip install -r {os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}')
    │    └ <function Command.execute at 0x0000021447F50438>
    └ <main.PythonManager object at 0x0000021454586088>

  File "F:\Genshin AI\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000214458039D8>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000021445803798>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x0000021448037558>}
    │    │        │    │        └ <Thread(Thread-9, started daemon 5836)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-9, started daemon 5836)>
    │    └ <function put_buttons.<locals>.click_callback at 0x00000214480375E8>
    └ <Thread(Thread-9, started daemon 5836)>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-Xqkg5Xz562', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x0000021448037558>

  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pages.MainPage object at 0x0000021450A9CD08>>]

> File "F:\Genshin AI\PGPL-2.0.0\pages.py", line 111, in _start
    PROGRAM_PYTHON_PATH = PythonManager(launching_config, pt).run()
                          │             │                 └ <main.ProgressTracker object at 0x0000021454585F08>
                          │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': True, 'Main': 'gen...
                          └ <class 'main.PythonManager'>

  File "F:\Genshin AI\PGPL-2.0.0\main.py", line 348, in run
    self.download_python_zip()
    │    └ <function PythonManager.download_python_zip at 0x000002144802F678>
    └ <main.PythonManager object at 0x0000021454586088>

  File "F:\Genshin AI\PGPL-2.0.0\main.py", line 263, in download_python_zip
    self.execute(f'"{self.python_path}" {os.path.join(ROOT_PATH, "toolkit", "get-pip.py")} --no-setuptools --no-wheel')
    │    └ <function Command.execute at 0x0000021447F50438>
    └ <main.PythonManager object at 0x0000021454586088>

  File "F:\Genshin AI\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError
Unhandled error in pywebio app
Traceback (most recent call last):
  File "F:\Genshin AI\PGPL-2.0.0\main.py", line 343, in run
    self.execute(f'"{self.python_path}" -m pip install -r {os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}')
  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\loguru\_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "F:\Genshin AI\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
  File "F:\Genshin AI\PGPL-2.0.0\pages.py", line 146, in _start
    raise e
  File "F:\Genshin AI\PGPL-2.0.0\pages.py", line 111, in _start
    PROGRAM_PYTHON_PATH = PythonManager(launching_config, pt).run()
  File "F:\Genshin AI\PGPL-2.0.0\main.py", line 348, in run
    self.download_python_zip()
  File "F:\Genshin AI\PGPL-2.0.0\main.py", line 263, in download_python_zip
    self.execute(f'"{self.python_path}" {os.path.join(ROOT_PATH, "toolkit", "get-pip.py")} --no-setuptools --no-wheel')
  File "F:\Genshin AI\PGPL-2.0.0\toolkit\lib\site-packages\loguru\_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "F:\Genshin AI\PGPL-2.0.0\utils.py", line 206, in execute
    raise ExecutionError
utils.ExecutionError

我已经把加速器关闭并重启之后还是会出现这种问题，希望大大可以帮忙看看

**Comment by infstellar** [comment]
去掉路径中的空格或者使用2.1.0版本
