### ISSUE TITLE
电脑上必须要安装python环境么？打开Launcher.exe直接报错

### ISSUE THREAD

**Issue by shihaoren** [infstellar/python-git-program-launcher#2]
系统：win11
按教程打开后直接无论是使用giachina还是链接都会提示错误，我尝试下载 https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip 到指定目录还是不可以

错误日志：
2023-07-12 00:00:26.502 | INFO     | __main__:run:477 - 你想要编辑设置或选择其他设置吗？
 无输入 3.8 秒后，PGPL将自动启动。 选项: ['y', 'n', '']
2023-07-12 00:00:27.751 | INFO     | logger:hr:66 - <<< DOWNLOADING PYTHON VERSION: 3.7.6 INTO D:\PGPL-1.0.0\TOOLKIT\PYTHON\3.7.6_GIA_LAUNCHER_DOWNLOAD_LIB >>>
2023-07-12 00:00:27.752 | WARNING  | __main__:run:325 - 请不要在下载python时退出程序。如果你不小心退出了或安装失败，请清空./toolkit/python文件夹中的对应文件夹后重试。
2023-07-12 00:00:27.753 | INFO     | __main__:download_python_zip:239 - url: https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip
2023-07-12 00:00:27.790 | INFO     | __main__:download_url:179 - 下载url:https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip -> D:\PGPL-1.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip
D:\PGPL-1.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 0.00B [00:00, ?B/s]Traceback (most recent call last):
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\connectionpool.py", line 776, in urlopen
    self._prepare_proxy(conn)
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\connectionpool.py", line 1041, in _prepare_proxy
    conn.connect()
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\connection.py", line 612, in connect
    self.sock = sock = self._connect_tls_proxy(self.host, sock)
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\connection.py", line 685, in _connect_tls_proxy
    tls_in_tls=False,
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\connection.py", line 786, in _ssl_wrap_socket_and_match_hostname
    tls_in_tls=tls_in_tls,
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\PGPL-1.0.0\toolkit\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "D:\PGPL-1.0.0\toolkit\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "D:\PGPL-1.0.0\toolkit\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\requests\adapters.py", line 497, in send
    chunked=chunked,
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mirrors.huaweicloud.com', port=443): Max retries exceeded with url: /python/3.7.6/python-3.7.6-embed-amd64.zip (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PGPL-1.0.0\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\PGPL-1.0.0\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PGPL-1.0.0\main.py", line 509, in <module>
    PythonManager(launching_config).run()
  File "D:\PGPL-1.0.0\main.py", line 326, in run
    self.download_python_zip()
  File "D:\PGPL-1.0.0\main.py", line 241, in download_python_zip
    download_url(url, file_name)
  File "D:\PGPL-1.0.0\main.py", line 183, in download_url
    req = requests.get(url, stream=True, verify=False)
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\PGPL-1.0.0\toolkit\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='mirrors.huaweicloud.com', port=443): Max retries exceeded with url: /python/3.7.6/python-3.7.6-embed-amd64.zip (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))
D:\PGPL-1.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 0.00B [00:00, ?B/s]
The program is over. This may be due to an error or an active end.

**Comment by Georgebillion** [comment]
如果你有Python的话，建议直接运行一下main.py

**Comment by infstellar** [comment]
清空./toolkit/python,关闭代理重试

**Comment by infstellar** [comment]
> File "D:\PGPL-1.0.0\toolkit\lib\ssl.py", line 870, in _create
self.do_handshake()
File "D:\PGPL-1.0.0\toolkit\lib\ssl.py", line 1139, in do_handshake
self._sslobj.do_handshake()

> requests.exceptions.ProxyError: HTTPSConnectionPool(host='mirrors.huaweicloud.com', port=443): Max retries exceeded with url: /python/3.7.6/python-3.7.6-embed-amd64.zip (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))

不要打开除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，它们会干扰SSL验证。

**Comment by Duyalun** [comment]
> > File "D:\PGPL-1.0.0\toolkit\lib\ssl.py", line 870, in _create
> > self.do_handshake()
> > File "D:\PGPL-1.0.0\toolkit\lib\ssl.py", line 1139, in do_handshake
> > self._sslobj.do_handshake()
> 
> > requests.exceptions.ProxyError: HTTPSConnectionPool(host='mirrors.huaweicloud.com', port=443): Max retries exceeded with url: /python/3.7.6/python-3.7.6-embed-amd64.zip (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))
> 
> 不要打开除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，它们会干扰SSL验证。

电脑上并没有这些，依旧不行

**Comment by infstellar** [comment]
试试新版本
