### ISSUE TITLE
运行Launcher.bat和Launcher.exe没有反应

### ISSUE THREAD

**Issue by huanyuechenmie** [infstellar/python-git-program-launcher#21]
是管理员权限运行的。
尝试运行过EnableLongPath.reg之后仍然无用。
2.1.0和2.0.0都是这样。
是需要安装什么吗？
以及日志文件不懂是如何打开的，如果排查问题需要，麻烦指点一下

**Comment by infstellar** [comment]
- 按GUI上的打开日志文件按钮
- 找到当天的日志文件(*.log)

**Comment by huanyuechenmie** [comment]
经过检查，Launcher.bat和Launcher.exe文件右键属性到最下面解除锁定就可以运行了

**Comment by huanyuechenmie** [comment]
> * 按GUI上的打开日志文件按钮
> * 找到当天的日志文件(*.log)

前面问题已经解决，但是运行程序时提示请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe。但是打开任务管理器，我打开的软件只有浏览器啊
2023-08-08 13:43:26.950 | INFO     | pgpl.webio:main:33 - webio已启动
2023-08-08 13:43:33.510 | INFO     | pgpl.logger:hr:73 - +------------------------------------------------------------------------------+
2023-08-08 13:43:33.513 | INFO     | pgpl.logger:hr:74 - |                    WELCOME TO PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-08-08 13:43:33.514 | INFO     | pgpl.logger:hr:75 - +------------------------------------------------------------------------------+
2023-08-08 13:43:33.516 | INFO     | pgpl.logger:hr:69 - <<< 该程序在GITHUB免费开源 >>>
2023-08-08 13:43:33.518 | INFO     | pgpl.logger:hr:69 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查看使用说明 >>>
2023-08-08 13:43:33.553 | INFO     | pgpl.utils:execute:236 - "D:/BaiduNetdiskDownload/PGPL-2.1.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/BaiduNetdiskDownload/PGPL-2.1.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py" --version
2023-08-08 13:43:34.299 | TRACE    | pgpl.utils:run_command:169 - pip 23.2.1 from D:\BaiduNetdiskDownload\PGPL-2.1.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\Lib\site-packages\pip (python 3.7)
2023-08-08 13:43:34.365 | INFO     | pgpl.utils:execute:262 - [ success ]
2023-08-08 13:43:34.367 | INFO     | pgpl.logger:hr:73 - +-------------------------------------------------+
2023-08-08 13:43:34.370 | INFO     | pgpl.logger:hr:74 - |                    PYTHON已安装                    |
2023-08-08 13:43:34.372 | INFO     | pgpl.logger:hr:75 - +-------------------------------------------------+
2023-08-08 13:43:34.374 | INFO     | pgpl.pages:_start:143 - {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'genshin_assistant.py', 'PypiMirror': '', 'PythonMirror': '', 'PythonVersion': '3.7.6', 'Repository': 'https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib', 'RequirementsFile': 'requirements.txt', 'Tag': ''}
2023-08-08 13:43:34.376 | INFO     | pgpl.logger:hr:69 - <<< 启动中... >>>
2023-08-08 13:43:34.378 | INFO     | pgpl.logger:hr:73 - +--------------------------------------------------------------------------+
2023-08-08 13:43:34.380 | INFO     | pgpl.logger:hr:74 - |                    UPDATE PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-08-08 13:43:34.383 | INFO     | pgpl.logger:hr:75 - +--------------------------------------------------------------------------+
2023-08-08 13:43:34.393 | INFO     | pgpl.logger:hr:73 - +----------------------------------------------+
2023-08-08 13:43:34.395 | INFO     | pgpl.logger:hr:74 - |                    GIT初始化                    |
2023-08-08 13:43:34.401 | INFO     | pgpl.logger:hr:75 - +----------------------------------------------+
2023-08-08 13:43:34.403 | INFO     | pgpl.utils:execute:236 - "D:/BaiduNetdiskDownload/PGPL-2.1.0/toolkit/Git/mingw64/bin/git.exe" init
2023-08-08 13:43:34.466 | TRACE    | pgpl.utils:run_command:169 - Reinitialized existing Git repository in D:/BaiduNetdiskDownload/PGPL-2.1.0/repositories/GIA_Launcher_Download_Lib/.git/
2023-08-08 13:43:34.469 | INFO     | pgpl.utils:execute:262 - [ success ]
2023-08-08 13:43:34.471 | INFO     | pgpl.logger:hr:65 - ==================== 设置GIT验证 ====================
2023-08-08 13:43:34.473 | INFO     | pgpl.utils:execute:236 - "D:/BaiduNetdiskDownload/PGPL-2.1.0/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
2023-08-08 13:43:34.509 | INFO     | pgpl.utils:execute:248 - [ allowed failure ], error_code: 5 stdout:  stderr: 
2023-08-08 13:43:34.510 | INFO     | pgpl.utils:execute:236 - "D:/BaiduNetdiskDownload/PGPL-2.1.0/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
2023-08-08 13:43:34.548 | INFO     | pgpl.utils:execute:248 - [ allowed failure ], error_code: 5 stdout:  stderr: 
2023-08-08 13:43:34.550 | INFO     | pgpl.logger:hr:65 - ==================== 设置GIT仓库 ====================
2023-08-08 13:43:34.552 | INFO     | pgpl.utils:execute:236 - "D:/BaiduNetdiskDownload/PGPL-2.1.0/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib
2023-08-08 13:43:34.588 | INFO     | pgpl.utils:execute:262 - [ success ]
2023-08-08 13:43:34.590 | INFO     | pgpl.logger:hr:65 - ==================== 获取仓库分支 ====================
2023-08-08 13:43:34.592 | INFO     | pgpl.utils:execute:236 - "D:/BaiduNetdiskDownload/PGPL-2.1.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
2023-08-08 13:43:36.763 | INFO     | pgpl.utils:execute:254 - [ failure ], error_code: 128 stdout:  stderr: fatal: unable to access 'https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/': Failed to connect to 127.0.0.1 port 31181: Connection refused

2023-08-08 13:43:36.766 | INFO     | pgpl.utils:show_error:198 - Update failed
2023-08-08 13:43:36.767 | INFO     | pgpl.utils:show_error:200 - 
2023-08-08 13:43:36.769 | INFO     | pgpl.utils:show_error:201 - Last command: "D:/BaiduNetdiskDownload/PGPL-2.1.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
error_code: 128
2023-08-08 13:43:36.771 | WARNING  | pgpl.utils:show_error:202 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-08-08 13:43:36.774 | ERROR    | pgpl.pages:_start:183 - 
Traceback (most recent call last):

  File "D:\BaiduNetdiskDownload\PGPL-2.1.0\toolkit\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001E39BE45048>
    └ <Thread(Thread-5, started daemon 11852)>

  File "D:\BaiduNetdiskDownload\PGPL-2.1.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001E39BE44DC8>
    └ <Thread(Thread-5, started daemon 11852)>

  File "D:\BaiduNetdiskDownload\PGPL-2.1.0\toolkit\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x000001E39E4A7CA8>}
    │    │        │    │        └ <Thread(Thread-5, started daemon 11852)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5, started daemon 11852)>
    │    └ <function put_buttons.<locals>.click_callback at 0x000001E39E4A78B8>
    └ <Thread(Thread-5, started daemon 11852)>

  File "D:\BaiduNetdiskDownload\PGPL-2.1.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-ZEt7P7gzkx', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x000001E39E4A7CA8>

  File "D:\BaiduNetdiskDownload\PGPL-2.1.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pgpl.pages.MainPage object at 0x000001E3A55C5F88>>]

> File "D:\BaiduNetdiskDownload\PGPL-2.1.0\pgpl\pages.py", line 149, in _start
    GitManager(launching_config, self.pt).git_install()
    │          │                 │    └ <pgpl.utils.ProgressTracker object at 0x000001E3A55C5FC8>
    │          │                 └ <pgpl.pages.MainPage object at 0x000001E3A55C5F88>
    │          └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class 'pgpl.managers.GitManager'>

  File "D:\BaiduNetdiskDownload\PGPL-2.1.0\pgpl\managers.py", line 115, in git_install
    keep_changes=self.KeepLocalChanges,
                 │    └ False
                 └ <pgpl.managers.GitManager object at 0x000001E3A55DC188>

  File "D:\BaiduNetdiskDownload\PGPL-2.1.0\pgpl\managers.py", line 71, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
    │    └ <function Command.execute at 0x000001E39E3A4F78>
    └ <pgpl.managers.GitManager object at 0x000001E3A55DC188>

  File "D:\BaiduNetdiskDownload\PGPL-2.1.0\pgpl\utils.py", line 259, in execute
    raise ExecutionError
          └ <class 'pgpl.utils.ExecutionError'>

pgpl.utils.ExecutionError

**Comment by huanyuechenmie** [comment]
这好久了啊

**Comment by jkjklmd** [comment]
我有一堆问题......... 我用Launcher.exe运行后 显示成功 启动中 但也就一直显示启动中 没反应 c++告诉我 在我的C盘\User\zjxjy\AppData\Local下缺少一个叫 getadmin.vbs脚本文件      然后就是显示启动中没反应
