### ISSUE TITLE
代理问题，没有使用Clash/加速器/网络连接管理等

### ISSUE THREAD

**Issue by Xrondev** [infstellar/python-git-program-launcher#27]
# 错误截图
<img width="243" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/61485096/d2b1e303-b323-4626-885e-d6d29a36ae81">

# Log
```
2023-08-30 14:16:57.028 | INFO     | pgpl.logger:hr:73 - +------------------------------------------------------------------------------+
2023-08-30 14:16:57.029 | INFO     | pgpl.logger:hr:74 - |                    WELCOME TO PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-08-30 14:16:57.029 | INFO     | pgpl.logger:hr:75 - +------------------------------------------------------------------------------+
2023-08-30 14:16:57.030 | INFO     | pgpl.logger:hr:69 - <<< 该程序在GITHUB免费开源 >>>
2023-08-30 14:16:57.030 | INFO     | pgpl.logger:hr:69 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查看使用说明 >>>
2023-08-30 14:16:57.039 | INFO     | pgpl.utils:execute:269 - "C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py" --version
2023-08-30 14:16:57.408 | TRACE    | pgpl.utils:run_command:195 - pip 23.2.1 from C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\Lib\site-packages\pip (python 3.7)
2023-08-30 14:16:57.428 | INFO     | pgpl.utils:execute:296 - [ success ]
2023-08-30 14:16:57.428 | INFO     | pgpl.logger:hr:73 - +-------------------------------------------------+
2023-08-30 14:16:57.428 | INFO     | pgpl.logger:hr:74 - |                    PYTHON已安装                    |
2023-08-30 14:16:57.428 | INFO     | pgpl.logger:hr:75 - +-------------------------------------------------+
2023-08-30 14:16:57.429 | INFO     | pgpl.pages:_start:144 - {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'genshin_assistant.py', 'PypiMirror': '', 'PythonMirror': '', 'PythonVersion': '3.7.6', 'Repository': 'https://github.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib', 'RequirementsFile': 'requirements.txt', 'Tag': '', 'UAC': True}
2023-08-30 14:16:57.429 | INFO     | pgpl.logger:hr:69 - <<< 启动中... >>>
2023-08-30 14:16:57.430 | INFO     | pgpl.logger:hr:73 - +--------------------------------------------------------------------------+
2023-08-30 14:16:57.430 | INFO     | pgpl.logger:hr:74 - |                    UPDATE PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-08-30 14:16:57.430 | INFO     | pgpl.logger:hr:75 - +--------------------------------------------------------------------------+
2023-08-30 14:16:57.430 | INFO     | pgpl.logger:hr:73 - +----------------------------------------------+
2023-08-30 14:16:57.431 | INFO     | pgpl.logger:hr:74 - |                    GIT初始化                    |
2023-08-30 14:16:57.431 | INFO     | pgpl.logger:hr:75 - +----------------------------------------------+
2023-08-30 14:16:57.431 | INFO     | pgpl.utils:execute:269 - "C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/toolkit/Git/mingw64/bin/git.exe" init
2023-08-30 14:16:57.515 | TRACE    | pgpl.utils:run_command:195 - Reinitialized existing Git repository in C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/repositories/GIA_Launcher_Download_Lib/.git/
2023-08-30 14:16:57.518 | INFO     | pgpl.utils:execute:296 - [ success ]
2023-08-30 14:16:57.518 | INFO     | pgpl.logger:hr:65 - ==================== 设置GIT验证 ====================
2023-08-30 14:16:57.518 | INFO     | pgpl.utils:execute:269 - "C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
2023-08-30 14:16:57.537 | INFO     | pgpl.utils:execute:281 - [ allowed failure ], error_code: 5 stdout:  stderr: 
2023-08-30 14:16:57.537 | INFO     | pgpl.utils:execute:269 - "C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
2023-08-30 14:16:57.547 | INFO     | pgpl.utils:execute:281 - [ allowed failure ], error_code: 5 stdout:  stderr: 
2023-08-30 14:16:57.547 | INFO     | pgpl.logger:hr:65 - ==================== 设置GIT仓库 ====================
2023-08-30 14:16:57.547 | INFO     | pgpl.utils:execute:269 - "C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://github.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib
2023-08-30 14:16:57.558 | INFO     | pgpl.utils:execute:296 - [ success ]
2023-08-30 14:16:57.559 | INFO     | pgpl.logger:hr:65 - ==================== 获取仓库分支 ====================
2023-08-30 14:16:57.559 | INFO     | pgpl.utils:execute:269 - "C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
2023-08-30 14:16:59.898 | INFO     | pgpl.utils:execute:287 - [ failure ], error_code: 128 stdout:  stderr: fatal: unable to access 'https://github.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/': Failed to connect to 127.0.0.1 port 7890: Connection refused

2023-08-30 14:16:59.898 | INFO     | pgpl.utils:show_error:231 - Update failed
2023-08-30 14:16:59.898 | INFO     | pgpl.utils:show_error:233 - 
2023-08-30 14:16:59.898 | INFO     | pgpl.utils:show_error:234 - Last command: "C:/Users/Xxxxxxx/Downloads/PGPL-2.2.1/PGPL-2.2.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
error_code: 128
2023-08-30 14:16:59.898 | INFO     | pgpl.utils:error_checking:226 - Running automatic error checking...
2023-08-30 14:16:59.899 | ERROR    | pgpl.pages:_start:196 - 
Traceback (most recent call last):

  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\toolkit\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000013AF6C24EE8>
    └ <Thread(Thread-4, started daemon 23532)>
  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\toolkit\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000013AF6C24CA8>
    └ <Thread(Thread-4, started daemon 23532)>
  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\toolkit\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x0000013AFA16AD38>}
    │    │        │    │        └ <Thread(Thread-4, started daemon 23532)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 23532)>
    │    └ <function put_buttons.<locals>.click_callback at 0x0000013AF945B288>
    └ <Thread(Thread-4, started daemon 23532)>
  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-r5RWmR5fSH', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x0000013AFA16AD38>
  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pgpl.pages.MainPage object at 0x0000013AF9449388>>]

> File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\pgpl\pages.py", line 150, in _start
    GitManager(launching_config, self.pt).git_install(allow_failure=("APR" in pin.pin[self.CHECKBOX_PIP]))
    │          │                 │    │                                       │   │   │    └ 'CHECKBOX_PIP'
    │          │                 │    │                                       │   │   └ <pgpl.pages.MainPage object at 0x0000013AF9449388>
    │          │                 │    │                                       │   └ <pywebio.pin.Pin_ object at 0x0000013AF92A0588>
    │          │                 │    │                                       └ <module 'pywebio.pin' from 'C:\\Users\\Xxxxxxx\\Downloads\\PGPL-2.2.1\\PGPL-2.2.0\\toolkit\\lib\\site-packages\\pywebio\\pin....
    │          │                 │    └ <pgpl.utils.ProgressTracker object at 0x0000013AF94493C8>
    │          │                 └ <pgpl.pages.MainPage object at 0x0000013AF9449388>
    │          └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class 'pgpl.managers.GitManager'>

  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\pgpl\managers.py", line 124, in git_install
    raise e

  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\pgpl\managers.py", line 118, in git_install
    keep_changes=self.KeepLocalChanges,
                 │    └ False
                 └ <pgpl.managers.GitManager object at 0x0000013A88AD2E08>

  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\pgpl\managers.py", line 71, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
    │    └ <function Command.execute at 0x0000013AF935A4C8>
    └ <pgpl.managers.GitManager object at 0x0000013A88AD2E08>

  File "C:\Users\Xxxxxxx\Downloads\PGPL-2.2.1\PGPL-2.2.0\pgpl\utils.py", line 293, in execute
    raise ExecutionError
          └ <class 'pgpl.utils.ExecutionError'>

pgpl.utils.ExecutionError
```

# 环境/补充信息

Windows 11， 人在HK可以裸连，没开Clash/加速器/网络连接管理/Watt Tool
设置中 代理已关闭，自动检测设置打开
gitchina配置文件也试过了，相同报错。
后台没有其他与代理相关的软件

---

# 既然他执意要走7890Clash，我打开Clash，选择DIRECT直连
<img width="242" alt="image" src="https://github.com/infstellar/python-git-program-launcher/assets/61485096/ab82e175-2682-4c63-95ad-ba2b732890f1">

请求解决方案

**Comment by infstellar** [comment]
emm,HK应该走国际链接,我改一下

**Comment by infstellar** [comment]
fixed
