### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 20: invalid continuation byte

### ISSUE THREAD

**Issue by qiujinchao** [infstellar/python-git-program-launcher#28]
日志内容：
2023-09-17 20:52:33.857 | INFO     | pgpl.logger:hr:73 - +------------------------------------------------------------------------------+
2023-09-17 20:52:33.863 | INFO     | pgpl.logger:hr:74 - |                    WELCOME TO PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-09-17 20:52:33.866 | INFO     | pgpl.logger:hr:75 - +------------------------------------------------------------------------------+
2023-09-17 20:52:33.869 | INFO     | pgpl.logger:hr:69 - <<< 该程序在GITHUB免费开源 >>>
2023-09-17 20:52:33.871 | INFO     | pgpl.logger:hr:69 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查看使用说明 >>>
2023-09-17 20:52:33.909 | INFO     | pgpl.utils:execute:281 - "D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py" --version
2023-09-17 20:52:34.027 | INFO     | pgpl.utils:execute:299 - [ failure ], error_code: 2 stdout:  stderr: D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe: can't open file 'D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py': [Errno 2] No such file or directory

2023-09-17 20:52:34.029 | INFO     | pgpl.utils:show_error:235 - Update failed
2023-09-17 20:52:34.031 | INFO     | pgpl.utils:show_error:237 - 
2023-09-17 20:52:34.033 | INFO     | pgpl.utils:show_error:238 - Last command: "D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py" --version
error_code: 2
2023-09-17 20:52:34.036 | INFO     | pgpl.utils:error_checking:230 - Running automatic error checking...
2023-09-17 20:52:34.039 | WARNING  | pgpl.managers:run:356 - pip失败，重装python
2023-09-17 20:52:34.054 | INFO     | pgpl.utils:verify_path:140 - dir D:\GAMES\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib has been created
2023-09-17 20:52:34.059 | INFO     | pgpl.utils:info:256 - url: https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip
2023-09-17 20:52:34.186 | INFO     | pgpl.utils:download_url:79 - 下载url:https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip -> D:\GAMES\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip
2023-09-17 20:52:35.196 | INFO     | pgpl.logger:hr:73 - +--------------------------------------------------------+
2023-09-17 20:52:35.196 | INFO     | pgpl.logger:hr:74 - |                    下载PYTHON成功，解压压缩包                    |
2023-09-17 20:52:35.196 | INFO     | pgpl.logger:hr:75 - +--------------------------------------------------------+
2023-09-17 20:52:35.359 | INFO     | pgpl.logger:hr:73 - +------------------------------------------------------+
2023-09-17 20:52:35.362 | INFO     | pgpl.logger:hr:74 - |                    INSTALLING PIP                    |
2023-09-17 20:52:35.365 | INFO     | pgpl.logger:hr:75 - +------------------------------------------------------+
2023-09-17 20:52:35.367 | INFO     | pgpl.utils:execute:281 - python "D:/GAMES/PGPL-2.2.0/toolkit/Lib/site-packages/pip/__main__.py" config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
2023-09-17 20:52:35.849 | TRACE    | pgpl.utils:run_command:199 - ['D:\\GAMES\\PGPL-2.2.0', 'D:\\GAMES\\PGPL-2.2.0\\toolkit', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\Lib', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\DLLs', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\Scripts']
2023-09-17 20:52:35.849 | ERROR    | pgpl.pages:_start:196 - 'utf-8' codec can't decode byte 0xf4 in position 20: invalid continuation byte
Traceback (most recent call last):

  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 354, in run
    self.execute(f'"{self.python_path}" "{self.python_folder}/Lib/site-packages/pip/__main__.py" --version')
    │    └ <function Command.execute at 0x00000153A4F91438>
    └ <pgpl.managers.PythonManager object at 0x00000153AC9CF348>

  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 305, in execute
    raise ExecutionError
          └ <class 'pgpl.utils.ExecutionError'>

pgpl.utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\GAMES\PGPL-2.2.0\toolkit\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000153A284FA68>
    └ <Thread(Thread-4, started daemon 7372)>
  File "D:\GAMES\PGPL-2.2.0\toolkit\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000153A284F828>
    └ <Thread(Thread-4, started daemon 7372)>
  File "D:\GAMES\PGPL-2.2.0\toolkit\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x00000153AC9A13A8>}
    │    │        │    │        └ <Thread(Thread-4, started daemon 7372)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 7372)>
    │    └ <function put_buttons.<locals>.click_callback at 0x00000153A5093168>
    └ <Thread(Thread-4, started daemon 7372)>
  File "D:\GAMES\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-AoeKJpq4g3', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x00000153AC9A13A8>
  File "D:\GAMES\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pgpl.pages.MainPage object at 0x00000153AC9B0708>>]

> File "D:\GAMES\PGPL-2.2.0\pgpl\pages.py", line 142, in _start
    PROGRAM_PYTHON_PATH = PythonManager(launching_config, self.pt).run()
                          │             │                 │    └ <pgpl.utils.ProgressTracker object at 0x00000153AC9B0D88>
                          │             │                 └ <pgpl.pages.MainPage object at 0x00000153AC9B0708>
                          │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': True, 'Main': 'gen...
                          └ <class 'pgpl.managers.PythonManager'>

  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 359, in run
    self.download_python_zip()
    │    └ <function PythonManager.download_python_zip at 0x00000153A507C798>
    └ <pgpl.managers.PythonManager object at 0x00000153AC9CF348>

  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 271, in download_python_zip
    self.execute(f'python "{pip_path}" config set global.index-url {self.PypiMirror}')
    │    └ <function Command.execute at 0x00000153A4F91438>
    └ <pgpl.managers.PythonManager object at 0x00000153AC9CF348>

  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 289, in execute
    error_code, stdout, stderr = run_command(command, self.progress_tracker)
                                 │           │        │    └ <pgpl.utils.ProgressTracker object at 0x00000153AC9B0D88>
                                 │           │        └ <pgpl.managers.PythonManager object at 0x00000153AC9CF348>
                                 │           └ 'python "D:/GAMES/PGPL-2.2.0/toolkit/Lib/site-packages/pip/__main__.py" config set global.index-url https://pypi.tuna.tsinghu...
                                 └ <function run_command at 0x00000153A4F844C8>

  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 193, in run_command
    if str(output, encoding='utf-8') == '' and (process.poll() is not None):
           │                                    │       └ <function Popen.poll at 0x00000153A2CA4438>
           │                                    └ <subprocess.Popen object at 0x00000153B4771548>
           └ b'Writing to C:\\Users\\\xf4\xc3\xbd\xf0\xb3\xac\\AppData\\Roaming\\pip\\pip.ini\r\n'

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 20: invalid continuation byte

**Comment by qiujinchao** [comment]
![捕获](https://github.com/infstellar/python-git-program-launcher/assets/32038026/d345c298-463c-4b1d-a680-aca6d648f6ea)

**Comment by qiujinchao** [comment]
DebugLauncher.bat上显示的信息

"D:\GAMES\PGPL-2.2.0"
['D:\\GAMES\\PGPL-2.2.0', 'D:\\GAMES\\PGPL-2.2.0\\toolkit', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\Lib', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\DLLs', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\Scripts']
zh_CN
python "D:\GAMES\PGPL-2.2.0/translation/msgfmt.py" -o "D:\GAMES\PGPL-2.2.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "D:\GAMES\PGPL-2.2.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
['D:\\GAMES\\PGPL-2.2.0', 'D:\\GAMES\\PGPL-2.2.0\\toolkit', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\Lib', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\DLLs', 'D:\\GAMES\\PGPL-2.2.0\\toolkit\\Scripts']
zh_CN
Running on all addresses.
Use http://192.168.2.6:22269/ to access the application
js: Error(%s) in dispatch command: %s TypeError: Cannot read property 'update_input' of undefined pin_update
2023-09-17 20:52:33.857 | INFO     | pgpl.logger:hr:73 - +------------------------------------------------------------------------------+
2023-09-17 20:52:33.863 | INFO     | pgpl.logger:hr:74 - |                    WELCOME TO PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-09-17 20:52:33.866 | INFO     | pgpl.logger:hr:75 - +------------------------------------------------------------------------------+
2023-09-17 20:52:33.869 | INFO     | pgpl.logger:hr:69 - <<< 该程序在GITHUB免费开源 >>>
2023-09-17 20:52:33.871 | INFO     | pgpl.logger:hr:69 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查看使用说明 >>>
2023-09-17 20:52:33.909 | INFO     | pgpl.utils:execute:281 - "D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py" --version
2023-09-17 20:52:34.027 | INFO     | pgpl.utils:execute:299 - [ failure ], error_code: 2 stdout:  stderr: D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe: can't open file 'D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py': [Errno 2] No such file or directory

2023-09-17 20:52:34.029 | INFO     | pgpl.utils:show_error:235 - Update failed
2023-09-17 20:52:34.031 | INFO     | pgpl.utils:show_error:237 -
2023-09-17 20:52:34.033 | INFO     | pgpl.utils:show_error:238 - Last command: "D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/GAMES/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py" --version
error_code: 2
2023-09-17 20:52:34.036 | INFO     | pgpl.utils:error_checking:230 - Running automatic error checking...
2023-09-17 20:52:34.039 | WARNING  | pgpl.managers:run:356 - pip失败，重装python
2023-09-17 20:52:34.054 | INFO     | pgpl.utils:verify_path:140 - dir D:\GAMES\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib has been created
2023-09-17 20:52:34.059 | INFO     | pgpl.utils:info:256 - url: https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip
2023-09-17 20:52:34.186 | INFO     | pgpl.utils:download_url:79 - 下载url:https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip -> D:\GAMES\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip
D:\GAMES\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 0.00B [00:00, ?B/s]D:\GAMES\PGPL-2.2.0\toolkit\lib\site-packages\urllib3\connectionpool.py:1102: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.huaweicloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  InsecureRequestWarning,
D:\GAMES\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 7.50MB [00:01, 7.48MB/s]
2023-09-17 20:52:35.196 | INFO     | pgpl.logger:hr:73 - +--------------------------------------------------------+
2023-09-17 20:52:35.196 | INFO     | pgpl.logger:hr:74 - |                    下载PYTHON成功，解压压缩包                    |
2023-09-17 20:52:35.196 | INFO     | pgpl.logger:hr:75 - +--------------------------------------------------------+
2023-09-17 20:52:35.359 | INFO     | pgpl.logger:hr:73 - +------------------------------------------------------+
2023-09-17 20:52:35.362 | INFO     | pgpl.logger:hr:74 - |                    INSTALLING PIP                    |
2023-09-17 20:52:35.365 | INFO     | pgpl.logger:hr:75 - +------------------------------------------------------+
2023-09-17 20:52:35.367 | INFO     | pgpl.utils:execute:281 - python "D:/GAMES/PGPL-2.2.0/toolkit/Lib/site-packages/pip/__main__.py" config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
2023-09-17 20:52:35.849 | ERROR    | pgpl.pages:_start:196 - 'utf-8' codec can't decode byte 0xf4 in position 20: invalid continuation byte
Traceback (most recent call last):

  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 354, in run
    self.execute(f'"{self.python_path}" "{self.python_folder}/Lib/site-packages/pip/__main__.py" --version')
    │    └ <function Command.execute at 0x00000153A4F91438>
    └ <pgpl.managers.PythonManager object at 0x00000153AC9CF348>

  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 305, in execute
    raise ExecutionError
          └ <class 'pgpl.utils.ExecutionError'>

pgpl.utils.ExecutionError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\GAMES\PGPL-2.2.0\toolkit\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000153A284FA68>
    └ <Thread(Thread-4, started daemon 7372)>
  File "D:\GAMES\PGPL-2.2.0\toolkit\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000153A284F828>
    └ <Thread(Thread-4, started daemon 7372)>
  File "D:\GAMES\PGPL-2.2.0\toolkit\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x00000153AC9A13A8>}
    │    │        │    │        └ <Thread(Thread-4, started daemon 7372)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 7372)>
    │    └ <function put_buttons.<locals>.click_callback at 0x00000153A5093168>
    └ <Thread(Thread-4, started daemon 7372)>
  File "D:\GAMES\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-AoeKJpq4g3', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x00000153AC9A13A8>
  File "D:\GAMES\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pgpl.pages.MainPage object at 0x00000153AC9B0708>>]

> File "D:\GAMES\PGPL-2.2.0\pgpl\pages.py", line 142, in _start
    PROGRAM_PYTHON_PATH = PythonManager(launching_config, self.pt).run()
                          │             │                 │    └ <pgpl.utils.ProgressTracker object at 0x00000153AC9B0D88>
                          │             │                 └ <pgpl.pages.MainPage object at 0x00000153AC9B0708>
                          │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': True, 'Main': 'gen...
                          └ <class 'pgpl.managers.PythonManager'>

  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 359, in run
    self.download_python_zip()
    │    └ <function PythonManager.download_python_zip at 0x00000153A507C798>
    └ <pgpl.managers.PythonManager object at 0x00000153AC9CF348>

  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 271, in download_python_zip
    self.execute(f'python "{pip_path}" config set global.index-url {self.PypiMirror}')
    │    └ <function Command.execute at 0x00000153A4F91438>
    └ <pgpl.managers.PythonManager object at 0x00000153AC9CF348>

  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 289, in execute
    error_code, stdout, stderr = run_command(command, self.progress_tracker)
                                 │           │        │    └ <pgpl.utils.ProgressTracker object at 0x00000153AC9B0D88>
                                 │           │        └ <pgpl.managers.PythonManager object at 0x00000153AC9CF348>
                                 │           └ 'python "D:/GAMES/PGPL-2.2.0/toolkit/Lib/site-packages/pip/__main__.py" config set global.index-url https://pypi.tuna.tsinghu...
                                 └ <function run_command at 0x00000153A4F844C8>

  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 193, in run_command
    if str(output, encoding='utf-8') == '' and (process.poll() is not None):
           │                                    │       └ <function Popen.poll at 0x00000153A2CA4438>
           │                                    └ <subprocess.Popen object at 0x00000153B4771548>
           └ b'Writing to C:\\Users\\\xf4\xc3\xbd\xf0\xb3\xac\\AppData\\Roaming\\pip\\pip.ini\r\n'

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 20: invalid continuation byte
Unhandled error in pywebio app
Traceback (most recent call last):
  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 354, in run
    self.execute(f'"{self.python_path}" "{self.python_folder}/Lib/site-packages/pip/__main__.py" --version')
  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 305, in execute
    raise ExecutionError
pgpl.utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GAMES\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
  File "D:\GAMES\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
  File "D:\GAMES\PGPL-2.2.0\pgpl\pages.py", line 201, in _start
    raise e
  File "D:\GAMES\PGPL-2.2.0\pgpl\pages.py", line 142, in _start
    PROGRAM_PYTHON_PATH = PythonManager(launching_config, self.pt).run()
  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 359, in run
    self.download_python_zip()
  File "D:\GAMES\PGPL-2.2.0\pgpl\managers.py", line 271, in download_python_zip
    self.execute(f'python "{pip_path}" config set global.index-url {self.PypiMirror}')
  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 289, in execute
    error_code, stdout, stderr = run_command(command, self.progress_tracker)
  File "D:\GAMES\PGPL-2.2.0\pgpl\utils.py", line 193, in run_command
    if str(output, encoding='utf-8') == '' and (process.poll() is not None):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 20: invalid continuation byte

**Comment by qiujinchao** [comment]
这个问题是什么情况，我遇到问题后也尝试下载最新的非Release源码替换，没什么效果，网上搜索出错描述也没找到正确的解决方案

**Comment by qiujinchao** [comment]
看起来像是文件文本编码问题，，，需要转文本编码吗

**Comment by infstellar** [comment]
>C:\Users\\xf4\xc3\xbd\xf0\xb3\xac\AppData\Roaming\pip\pip.ini\r\n'

可能是用户名含有中文字符?

**Comment by qiujinchao** [comment]
的确，用户名是中文的，我特地把程序放到了D盘没有中文名称的路径下，只是没想到这程序会用到Users路径下的程序，我想个办法处理下

**Comment by DreamBroke** [comment]
请问最终是怎么解决了吗？

**Comment by DreamBroke** [comment]
我提了一个PR，我这么修改后，可以正常启动了：https://github.com/infstellar/python-git-program-launcher/pull/35

**Comment by infstellar** [comment]
fixed in v2.3 & #35
