### ISSUE TITLE
error_code: 128   请按任意键继续. . .

### ISSUE THREAD

**Issue by GenLiya** [infstellar/python-git-program-launcher#3]
"C:\Users\刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2"
zh_CN
python "C:\Users\刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2/translation/msgfmt.py" -o "C:\Users\刘
星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "C:\Users\
刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
zh_CN
2023-07-12 14:07:54.113 | INFO     | logger:hr:70 - +------------------------------------------------------------------------------+
2023-07-12 14:07:54.115 | INFO     | logger:hr:71 - |                    WELCOME TO PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-07-12 14:07:54.115 | INFO     | logger:hr:72 - +------------------------------------------------------------------------------+
2023-07-12 14:07:54.116 | INFO     | logger:hr:66 - <<< 该程序在GITHUB免费开源 >>>
2023-07-12 14:07:54.117 | INFO     | logger:hr:66 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查
看使用说明 >>>
2023-07-12 14:07:54.118 | INFO     | __main__:run:487 - 当前配置: giachina
2023-07-12 14:07:54.118 | INFO     | __main__:run:488 - 你想要编辑设置或选择其他设置吗？
 无输入 -0.0 秒后，PGPL将自动启动。 选项: ['y', 'n', '']
2023-07-12 14:07:59.127 | INFO     | utils:execute:171 - "C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r C:/Users/刘星宇/Desktop/个人/刘
星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/basic_requirements.txt
Requirement already satisfied: lxml in c:\users\刘星宇\desktop\个人\刘星宇\原神\攻略\自动\pgpl-1.0.2\pgpl-1.0.2\toolkit\python\3.7.6_gia_launcher_download_lib\lib\site-packages (from -r C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/basic_requirements.txt (line 1)) (4.9.3)
Requirement already satisfied: future in c:\users\刘星宇\desktop\个人\刘星宇\原神\攻略\自动\pgpl-1.0.2\pgpl-1.0.2\toolkit\python\3.7.6_gia_launcher_download_lib\lib\site-packages (from -r C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/basic_requirements.txt (line 2)) (0.18.3)
Requirement already satisfied: urllib3 in c:\users\刘星宇\desktop\个人\刘星宇\原神\攻略\自动\pgpl-1.0.2\pgpl-1.0.2\toolkit\python\3.7.6_gia_launcher_download_lib\lib\site-packages (from -r C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/basic_requirements.txt (line 3)) (2.0.3)
2023-07-12 14:07:59.807 | INFO     | utils:execute:182 - [ success ]
2023-07-12 14:07:59.807 | INFO     | __main__:<module>:521 - {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'genshin_assistant.py', 'PypiMirror': 'AUTO', 'PythonMirror': 'AUTO', 'PythonVersion': '3.7.6', 'Repository': 'https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib', 'RequirementsFile': 'requirements.txt', 'Tag': ''}
2023-07-12 14:07:59.808 | INFO     | logger:hr:66 - <<< 启动中... >>>
2023-07-12 14:07:59.809 | INFO     | logger:hr:70 - +--------------------------------------------------------------------------+
2023-07-12 14:07:59.810 | INFO     | logger:hr:71 - |                    UPDATE PYTHON-GIT-PROGRAM-LAUNCHER
       |
2023-07-12 14:07:59.810 | INFO     | logger:hr:72 - +--------------------------------------------------------------------------+
2023-07-12 14:07:59.811 | INFO     | logger:hr:66 - <<< GIT初始化 >>>
2023-07-12 14:07:59.812 | INFO     | utils:execute:171 - "C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/repositories/GIA_Launcher_Download_Lib/.git/
2023-07-12 14:07:59.842 | INFO     | utils:execute:182 - [ success ]
2023-07-12 14:07:59.843 | INFO     | logger:hr:62 - ==================== 设置GIT验证 ====================
2023-07-12 14:07:59.844 | INFO     | utils:execute:171 - "C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
2023-07-12 14:07:59.866 | INFO     | utils:execute:175 - [ allowed failure ], error_code: 5
2023-07-12 14:07:59.867 | INFO     | utils:execute:171 - "C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
2023-07-12 14:07:59.889 | INFO     | utils:execute:175 - [ allowed failure ], error_code: 5
2023-07-12 14:07:59.889 | INFO     | logger:hr:62 - ==================== 设置GIT仓库 ====================
2023-07-12 14:07:59.890 | INFO     | utils:execute:171 - "C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib
2023-07-12 14:07:59.913 | INFO     | utils:execute:182 - [ success ]
2023-07-12 14:07:59.914 | INFO     | logger:hr:62 - ==================== 获取仓库分支 ====================
2023-07-12 14:07:59.915 | INFO     | utils:execute:171 - "C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/Git/mingw64/bin/git.exe" fetch origin main
fatal: unable to access 'https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/': OpenSSL SSL_connect: Connection was aborted in connection to gitee.com:443
2023-07-12 14:08:19.236 | INFO     | utils:execute:178 - [ failure ], error_code: 128
2023-07-12 14:08:19.237 | INFO     | utils:show_error:145 - Update failed
2023-07-12 14:08:19.238 | INFO     | utils:show_error:147 -
2023-07-12 14:08:19.238 | INFO     | utils:show_error:148 - Last command: "C:/Users/刘星宇/Desktop/个人/刘星宇/原神/攻略/自动/PGPL-1.0.2/PGPL-1.0.2/toolkit/Git/mingw64/bin/git.exe" fetch origin main
error_code: 128
2023-07-12 14:08:19.239 | INFO     | utils:show_error:150 - Please check your NETWORK ENVIROUMENT and re-open Launcher.exe
Traceback (most recent call last):
  File "C:\Users\刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2\main.py", line 527, in <module>
    GitManager(launching_config).git_install()
  File "C:\Users\刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2\main.py", line 115, in git_install
    keep_changes=self.KeepLocalChanges,
  File "C:\Users\刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2\main.py", line 71, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
  File "C:\Users\刘星宇\Desktop\个人\刘星宇\原神\攻略\自动\PGPL-1.0.2\PGPL-1.0.2\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError
The program is over. This may be due to an error or an active end.
请按任意键继续. . .

**Comment by infstellar** [comment]
关代理重试

**Comment by infstellar** [comment]
> fatal: unable to access 'https://gitee.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/': OpenSSL SSL_connect: Connection was aborted in connection to gitee.com:443

不要打开除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，它们会干扰SSL验证。

**Comment by infstellar** [comment]
另外路径不能有中文
