### ISSUE TITLE
找不到句柄

### ISSUE THREAD

**Issue by moyemoya** [infstellar/python-git-program-launcher#4]
"E:\下载\PGPL-1.0.2\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe" genshin_assistant.py
zh_CN
python "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib/source/msgfmt.py" -o "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
2023-07-12 18:43:56.333 | WARNING  | source.common.static_lib:get_handle:27 - 找不到句柄
2023-07-12 18:43:56.343 | INFO     | source.interaction.interaction_core:__init__:72 - InteractionBGD created
[ WARN:0@1.181] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('E:\涓嬭浇\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\assets/imgs/Windows/Combat/common/AreaCombatQ1.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "genshin_assistant.py", line 9, in <module>
    from source.webio import webio
  File "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\source\webio\webio.py", line 15, in <module>
    from source.webio.webpages.video2path import VideoToPathPage
  File "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\source\webio\webpages\video2path.py", line 6, in <module>
    from source.ui.ui import ui_control
  File "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\source\ui\ui.py", line 2, in <module>
    from source.manager.asset import *
  File "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\source\manager\asset.py", line 32, in <module>
    character_q_skills = PosiTemplate(img_path=fr"{ASSETS_PATH}/imgs/Windows/Combat/common/AreaCombatQ1.jpg")
  File "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\source\manager\posi_manager.py", line 34, in __init__
    self.add_posi(posi=posi, img_path=img_path)
  File "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\source\manager\posi_manager.py", line 48, in add_posi
    position = get_bbox(image, black_offset=18)
  File "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\source\util.py", line 436, in get_bbox
    if image_channel(image) == 3:
  File "E:\下载\PGPL-1.0.2\repositories\GIA_Launcher_Download_Lib\source\util.py", line 459, in image_channel
    return image.shape[2] if len(image.shape) == 3 else 0
AttributeError: 'NoneType' object has no attribute 'shape'
The program is over. This may be due to an error or an active end.
请按任意键继续. . .

**Comment by infstellar** [comment]
路径不能有中文
