### ISSUE TITLE
我电脑上并没有运行加速器等软件，依旧提示错误

### ISSUE THREAD

**Issue by Duyalun** [infstellar/python-git-program-launcher#5]
他甚至已经开始下载了，但是依旧出错
错误日志：
"D:\Program Files (x86)\PGPL-1.0.3"
zh_CN
python "D:\Program Files (x86)\PGPL-1.0.3/translation/msgfmt.py" -o "D:\Program Files (x86)\PGPL-1.0.3\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "D:\Program Files (x86)\PGPL-1.0.3\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
zh_CN
2023-07-12 20:10:20.567 | INFO     | logger:hr:70 - +------------------------------------------------------------------------------+
2023-07-12 20:10:20.567 | INFO     | logger:hr:71 - |                    WELCOME TO PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-07-12 20:10:20.568 | INFO     | logger:hr:72 - +------------------------------------------------------------------------------+
2023-07-12 20:10:20.569 | INFO     | logger:hr:66 - <<< 该程序在GITHUB免费开源 >>>
2023-07-12 20:10:20.569 | INFO     | logger:hr:66 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查 看使用说明 >>>
2023-07-12 20:10:20.570 | INFO     | __main__:run:489 - 当前配置: giachina
2023-07-12 20:10:20.571 | INFO     | __main__:run:490 - 你想要编辑设置或选择其他设置吗？
 无输入 2.3 秒后，PGPL将自动启动。 选项: ['y', 'n', '']n
2023-07-12 20:10:23.279 | INFO     | utils:execute:171 - "D:/Program Files (x86)/PGPL-1.0.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r D:/Program Files (x86)/PGPL-1.0.3/toolkit/basic_requirements.txt
D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe: No module named pip
2023-07-12 20:10:23.317 | INFO     | utils:execute:178 - [ failure ], error_code: 1
2023-07-12 20:10:23.318 | INFO     | utils:show_error:145 - Update failed
2023-07-12 20:10:23.318 | INFO     | utils:show_error:147 -
2023-07-12 20:10:23.319 | INFO     | utils:show_error:148 - Last command: "D:/Program Files (x86)/PGPL-1.0.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r D:/Program Files (x86)/PGPL-1.0.3/toolkit/basic_requirements.txt
error_code: 1
2023-07-12 20:10:23.320 | WARNING  | utils:show_error:149 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-12 20:10:23.320 | WARNING  | utils:show_error:150 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-12 20:10:23.321 | WARNING  | utils:show_error:151 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-12 20:10:23.322 | ERROR    | __main__:run:333 - An error has been caught in function 'run', process 'MainProcess' (9704), thread 'MainThread' (9652):
Traceback (most recent call last):

  File "D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
                └ ModuleSpec(name='main', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000016BB4763548>, origin='D:\\Progra...

  File "D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x0000016BB4911810, file "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 1>

  File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 522, in <module>
    PythonManager(launching_config).run()
    │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class '__main__.PythonManager'>

> File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 333, in run
    self.execute(f'"{self.python_path}" -m pip install -r {os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}')
    │    └ <function Command.execute at 0x0000016BB6872558>
    └ <__main__.PythonManager object at 0x0000016BB65DE848>

  File "D:\Program Files (x86)\PGPL-1.0.3\utils.py", line 180, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError
2023-07-12 20:10:23.338 | WARNING  | __main__:run:335 - pip fail, reinstall python
2023-07-12 20:10:23.344 | INFO     | utils:verify_path:92 - dir D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib has been created
2023-07-12 20:10:23.346 | INFO     | __main__:download_python_zip:243 - url: https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip
2023-07-12 20:10:23.403 | INFO     | __main__:download_url:181 - 下载url:https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip -> D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip
D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 0.00B [00:00, ?B/s]D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\site-packages\urllib3\connectionpool.py:1102: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.huaweicloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  InsecureRequestWarning,
D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 1.02kB [00:00, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 97.3kB [00:00, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 212kB [00:00, 7D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 327kB [00:00, 8D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 441kB [00:00, 9D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 589kB [00:00, 1D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 720kB [00:00, 1D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 884kB [00:00, 1D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 1.03MB [00:00, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 1.21MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 1.39MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 1.59MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 1.78MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 2.00MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 2.23MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 2.44MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 2.69MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 2.93MB [00:01, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 3.19MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 3.46MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 3.73MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 4.01MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 4.31MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 4.62MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 4.93MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 5.27MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 5.60MB [00:02, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 5.96MB [00:03, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 6.32MB [00:03, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 6.70MB [00:03, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 7.09MB [00:03, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 7.49MB [00:03, D:\Program Files (x86)\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip: 7.50MB [00:03, 2.17MB/s]
2023-07-12 20:10:26.869 | INFO     | logger:hr:66 - <<< 下载PYTHON成功，解压压缩包 >>>
2023-07-12 20:10:26.956 | INFO     | logger:hr:66 - <<< INSTALLING PIP >>>
2023-07-12 20:10:26.956 | INFO     | utils:execute:171 - "D:/Program Files (x86)/PGPL-1.0.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" D:/Program Files (x86)/PGPL-1.0.3/toolkit/get-pip.py --no-setuptools --no-wheel
D:/Program Files (x86)/PGPL-1.0.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe: can't open file 'D:/Program': [Errno 2] No such file or directory
2023-07-12 20:10:27.003 | INFO     | utils:execute:178 - [ failure ], error_code: 2
2023-07-12 20:10:27.003 | INFO     | utils:show_error:145 - Update failed
2023-07-12 20:10:27.004 | INFO     | utils:show_error:147 -
2023-07-12 20:10:27.005 | INFO     | utils:show_error:148 - Last command: "D:/Program Files (x86)/PGPL-1.0.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" D:/Program Files (x86)/PGPL-1.0.3/toolkit/get-pip.py --no-setuptools --no-wheel
error_code: 2
2023-07-12 20:10:27.006 | WARNING  | utils:show_error:149 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-12 20:10:27.007 | WARNING  | utils:show_error:150 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-12 20:10:27.008 | WARNING  | utils:show_error:151 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-12 20:10:27.009 | ERROR    | __main__:download_python_zip:253 - An error has been caught in function 'download_python_zip', process 'MainProcess' (9704), thread 'MainThread' (9652):
Traceback (most recent call last):

  File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 333, in run
    self.execute(f'"{self.python_path}" -m pip install -r {os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}')
    │    └ <function Command.execute at 0x0000016BB6872558>
    └ <__main__.PythonManager object at 0x0000016BB65DE848>

  File "D:\Program Files (x86)\PGPL-1.0.3\utils.py", line 180, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
                └ ModuleSpec(name='main', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000016BB4763548>, origin='D:\\Progra...

  File "D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x0000016BB4911810, file "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 1>

  File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 522, in <module>
    PythonManager(launching_config).run()
    │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class '__main__.PythonManager'>

  File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 338, in run
    self.download_python_zip()
    │    └ <function PythonManager.download_python_zip at 0x0000016BB6927948>
    └ <__main__.PythonManager object at 0x0000016BB65DE848>

> File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 253, in download_python_zip
    self.execute(f'"{self.python_path}" {os.path.join(ROOT_PATH, "toolkit", "get-pip.py")} --no-setuptools --no-wheel')
    │    └ <function Command.execute at 0x0000016BB6872558>
    └ <__main__.PythonManager object at 0x0000016BB65DE848>

  File "D:\Program Files (x86)\PGPL-1.0.3\utils.py", line 180, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError
Traceback (most recent call last):
  File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 333, in run
    self.execute(f'"{self.python_path}" -m pip install -r {os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}')
  File "D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\site-packages\loguru\_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "D:\Program Files (x86)\PGPL-1.0.3\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 522, in <module>
    PythonManager(launching_config).run()
  File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 338, in run
    self.download_python_zip()
  File "D:\Program Files (x86)\PGPL-1.0.3\main.py", line 253, in download_python_zip
    self.execute(f'"{self.python_path}" {os.path.join(ROOT_PATH, "toolkit", "get-pip.py")} --no-setuptools --no-wheel')
  File "D:\Program Files (x86)\PGPL-1.0.3\toolkit\lib\site-packages\loguru\_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "D:\Program Files (x86)\PGPL-1.0.3\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError
The program is over. This may be due to an error or an active end.
请按任意键继续. . .

**Comment by infstellar** [comment]
emm 暂时不能处理有空格的路径 之后会修

**Comment by Duyalun** [comment]
> emm 暂时不能处理有空格的路径 之后会修

明白了，我换个路径再试下
