### ISSUE TITLE
关于路径带空格的启动问题

### ISSUE THREAD

**Issue by BakaJzon** [infstellar/python-git-program-launcher#7]
这都3202年了，还有程序不支持带空格路径。。。
can't open file 'E:/Program'
``` log
2023-07-13 10:57:54.527 | INFO     | logger:hr:66 - <<< 下载PYTHON成功，解压压缩包 >>>
2023-07-13 10:57:54.641 | INFO     | logger:hr:66 - <<< INSTALLING PIP >>>
2023-07-13 10:57:54.642 | INFO     | utils:execute:171 - "E:/Program Files/PGPL-1.0.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" E:/Program Files/PGPL-1.0.3/toolkit/get-pip.py --no-setuptools --no-wheel
E:/Program Files/PGPL-1.0.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe: can't open file 'E:/Program': [Errno 2] No such file or directory
2023-07-13 10:57:54.710 | INFO     | utils:execute:178 - [ failure ], error_code: 2
2023-07-13 10:57:54.711 | INFO     | utils:show_error:145 - Update failed
2023-07-13 10:57:54.712 | INFO     | utils:show_error:147 -
2023-07-13 10:57:54.712 | INFO     | utils:show_error:148 - Last command: "E:/Program Files/PGPL-1.0.3/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" E:/Program Files/PGPL-1.0.3/toolkit/get-pip.py --no-setuptools --no-wheel
error_code: 2
2023-07-13 10:57:54.713 | WARNING  | utils:show_error:149 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-13 10:57:54.714 | WARNING  | utils:show_error:150 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-13 10:57:54.715 | WARNING  | utils:show_error:151 - 请检查你的网络环境，彻底关闭除了Watt Toolkit之外的所有可能干扰网络连接的软件，包括Clash/游戏加速器/网络连接管理/下载加速器等，然后重新打开Launcher.exe
2023-07-13 10:57:54.716 | ERROR    | __main__:download_python_zip:253 - An error has been caught in function 'download_python_zip', process 'MainProcess' (20220), thread 'MainThread' (9072):
Traceback (most recent call last):

  File "E:\Program Files\PGPL-1.0.3\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
                └ ModuleSpec(name='main', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000013564742608>, origin='E:\\Progra...

  File "E:\Program Files\PGPL-1.0.3\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x00000135648F0C90, file "E:\Program Files\PGPL-1.0.3\main.py", line 1>

  File "E:\Program Files\PGPL-1.0.3\main.py", line 522, in <module>
    PythonManager(launching_config).run()
    │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class '__main__.PythonManager'>

  File "E:\Program Files\PGPL-1.0.3\main.py", line 330, in run
    self.download_python_zip()
    │    └ <function PythonManager.download_python_zip at 0x00000135668F3D38>
    └ <__main__.PythonManager object at 0x00000135648F55C8>

> File "E:\Program Files\PGPL-1.0.3\main.py", line 253, in download_python_zip
    self.execute(f'"{self.python_path}" {os.path.join(ROOT_PATH, "toolkit", "get-pip.py")} --no-setuptools --no-wheel')
    │    └ <function Command.execute at 0x00000135668401F8>
    └ <__main__.PythonManager object at 0x00000135648F55C8>

  File "E:\Program Files\PGPL-1.0.3\utils.py", line 180, in execute
    raise ExecutionError
          └ <class 'utils.ExecutionError'>

utils.ExecutionError
Traceback (most recent call last):
  File "E:\Program Files\PGPL-1.0.3\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Program Files\PGPL-1.0.3\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Program Files\PGPL-1.0.3\main.py", line 522, in <module>
    PythonManager(launching_config).run()
  File "E:\Program Files\PGPL-1.0.3\main.py", line 330, in run
    self.download_python_zip()
  File "E:\Program Files\PGPL-1.0.3\main.py", line 253, in download_python_zip
    self.execute(f'"{self.python_path}" {os.path.join(ROOT_PATH, "toolkit", "get-pip.py")} --no-setuptools --no-wheel')
  File "E:\Program Files\PGPL-1.0.3\toolkit\lib\site-packages\loguru\_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "E:\Program Files\PGPL-1.0.3\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError
```

**Comment by infstellar** [comment]
你可以提交一个PR来修复该问题

**Comment by BakaJzon** [comment]
邪门，我改了 main.py 后
 ``` log
2023-07-13 12:38:41.113 | INFO     | logger:hr:66 - <<< 下载PYTHON成功，解压压缩包 >>>
2023-07-13 12:38:41.249 | INFO     | logger:hr:66 - <<< INSTALLING PIP >>>
2023-07-13 12:38:41.249 | INFO     | utils:execute:171 - "E:\Program Files\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe" "E:\Program Files\PGPL-1.0.3\toolkit\get-pip.py" --no-setuptools --no-wheel
'E:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-07-13 12:38:41.258 | INFO     | utils:execute:178 - [ failure ], error_code: 1
2023-07-13 12:38:41.258 | INFO     | utils:show_error:145 - Update failed
2023-07-13 12:38:41.259 | INFO     | utils:show_error:147 -
2023-07-13 12:38:41.259 | INFO     | utils:show_error:148 - Last command: "E:\Program Files\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe" "E:\Program Files\PGPL-1.0.3\toolkit\get-pip.py" --no-setuptools --no-wheel
error_code: 1
```
但是用cmd执行
``` log
C:\Users\bkjzon>"E:\Program Files\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe" "E:\Program Files\PGPL-1.0.3\toolkit\get-pip.py" --no-setuptools --no-wheel
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  WARNING: The scripts pip.exe, pip3.7.exe and pip3.exe are installed in 'E:\Program Files\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.1.2

C:\Users\bkjzon>echo %errorlevel%
0
```

**Comment by caoyuan5113** [comment]
原来是不能带空格，建议作者写道首页第一行 我治了一下午QAQ

**Comment by BakaJzon** [comment]
@infstellar 有个想法，因为Launcher.bat 中有一行`cd /d "%_root%"`，是不是可以将所有绝对路径换成相对路径？

另，我测试了os.system()，这个好像有点问题：
```
>>> os.system('"E:/Program Files/python-git-program-launcher/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe"')
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
>>> ^Z^Z

0
>>> os.system('"E:/Program Files/python-git-program-launcher/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" a_param')
E:/Program Files/python-git-program-launcher/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe: can't open file 'a_param': [Errno 2] No such file or directory
2 //这个是正常的

```

**Comment by infstellar** [comment]
真就玄学问题

**Comment by Narushio** [comment]
我刚想提这个issue来着，结果已经有人提了

**Comment by BakaJzon** [comment]
> 真就玄学问题

我看代码util里面把runcommand注释掉了。
这有什么问题吗？要不尝试一下subprocess?

**Comment by kohaku-2434** [comment]
我是佛了 排查了2个小时 最后没办法打算来逐条查issue发现了这条  结果我把文件夹名的Genshin Impact中间空格换掉果然就行了 这问题属于是复古潮流了
