### ISSUE TITLE
安装时DLL load failed: 找不到指定的模块

### ISSUE THREAD

**Issue by hrzzzzzzzz** [infstellar/python-git-program-launcher#8]
2023-07-13 11:14:45.796 | INFO     | utils:execute:183 - [ success ]
2023-07-13 11:14:45.796 | INFO     | logger:hr:70 - +----------------------------------------------------------------------------------------------------+
2023-07-13 11:14:45.796 | INFO     | logger:hr:71 - |                    SUCCESSFULLY INSTALL. ACTIVATING PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-07-13 11:14:45.811 | INFO     | logger:hr:72 - +----------------------------------------------------------------------------------------------------+
"E:\LenovoQMDownload\m\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe" genshin_assistant.py
Traceback (most recent call last):
  File "genshin_assistant.py", line 9, in <module>
    from source.webio import webio
  File "E:\LenovoQMDownload\m\repositories\GIA_Launcher_Download_Lib\source\webio\__init__.py", line 1, in <module>
    from source.webio.page_manager import PageManager
  File "E:\LenovoQMDownload\m\repositories\GIA_Launcher_Download_Lib\source\webio\page_manager.py", line 4, in <module>
    from source.util import *
  File "E:\LenovoQMDownload\m\repositories\GIA_Launcher_Download_Lib\source\util.py", line 3, in <module>
    import win32gui, win32process, psutil, ctypes, pickle, traceback
ImportError: DLL load failed: 找不到指定的模块。
The program is over. This may be due to an error or an active end.
请按任意键继续. . .

**Comment by infstellar** [comment]
重启可能能解决问题
