### ISSUE TITLE
运行Launcher.exe报错AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by zoulu995** [infstellar/python-git-program-launcher#9]
win10电脑安装时报错~
```
2023-07-15 14:06:59.535 | INFO     | logger:hr:72 - +----------------------------------------------------------------------------------------------------+
"D:\ChromeDonwload\安装包\PGPL-1.0.3\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe" genshin_assistant.py
zh_CN
python "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib/source/msgfmt.py" -o "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
2023-07-15 14:07:01.806 | INFO     | source.interaction.interaction_core:__init__:72 - InteractionBGD created
[ WARN:0@2.198] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('D:\ChromeDonwload\瀹夎鍖匼PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\assets/imgs/Windows/Combat/common/AreaCombatQ1.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "genshin_assistant.py", line 9, in <module>
    from source.webio import webio
  File "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\source\webio\webio.py", line 15, in <module>
    from source.webio.webpages.video2path import VideoToPathPage
  File "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\source\webio\webpages\video2path.py", line 6, in <module>
    from source.ui.ui import ui_control
  File "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\source\ui\ui.py", line 2, in <module>
    from source.manager.asset import *
  File "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\source\manager\asset.py", line 32, in <module>
    character_q_skills = PosiTemplate(img_path=fr"{ASSETS_PATH}/imgs/Windows/Combat/common/AreaCombatQ1.jpg")
  File "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\source\manager\posi_manager.py", line 34, in __init__
    self.add_posi(posi=posi, img_path=img_path)
  File "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\source\manager\posi_manager.py", line 48, in add_posi
    position = get_bbox(image, black_offset=18)
  File "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\source\util.py", line 436, in get_bbox
    if image_channel(image) == 3:
  File "D:\ChromeDonwload\安装包\PGPL-1.0.3\repositories\GIA_Launcher_Download_Lib\source\util.py", line 459, in image_channel
    return image.shape[2] if len(image.shape) == 3 else 0
AttributeError: 'NoneType' object has no attribute 'shape'
The program is over. This may be due to an error or an active end.
```

**Comment by zoulu995** [comment]
原因是路径名存在中文，换成英文就可以了
